var ItemPrefixes = [
    'Broken',
    'Crude',
    'Divine',
    'Brilliant',
    'Holy',
    'Chaotic',
    'Unholy',
    'Shining',
    'Godly',
    'Unjust',
    'Fierce',
    'Exceptional',
    'Fine',
    'Marvelous',
    'Blessed'
];

var ItemTypes = [
    'Blade',
    'Bow',
    'Great Axe',
    'Hammer',
    'Crossbow',
    'Longsword',
    'Dagger',
    'Hand Axe',
    'Greatsword',
    'Shortsword',
    'Warhammer',
    'Mace',
    'Flail',
    'Maul',
    'Morning Star',
    'Glaive',
    'Halberd',
    'Lance',
    'Hand Cannon',
    'Throwing Spear',
    'Falchion',
    'Sabre',
    'Claymore',
    'Bastard Sword',
    'Katana',
    'Throwing Knife'
];

var ItemSuffixes = [
    'of Divinity',
    'of Burning Fury',
    'of the Forest',
    'of Dimensions',
    'of Celestial Mysteries',
    'of Wailing Souls',
    'of X\'lotohl\'loth',
    'of the Deep',
    'of Doom',
    'of the Long Road',
    'of the Council of Seers',
    'of Arcane Rituals',
    'of Mindbending',
    'of Sols',
    'of the High Seas',
    'of Regeneration',
    'of Healing',
    'of Venomous Intent',
    'of Zh\'ox\'rothl',
    'of M\'ambuu, the Reverent',
];